name: ci

on:
  push:
   paths:
    - src/**
   branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: commit ID
        shell: bash
        run: |
          echo "COMMID_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jabord11125/pythonapp:${{ env.COMMID_ID }}